name: CMake Build and Test

on:
  push:
    branches: main
  #pull_request:
    #branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      
      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up CMake
      run: sudo apt-get install -y cmake

    - name: Configure and Build
      working-directory: ${{ github.workspace }}
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run Tests
      working-directory: ${{ github.workspace }}/build
      run: ./gs_test
